directories:
  output: dist
  buildResources: build
publish:
  - provider: generic
    url: 'https://mindsolution-updater.herokuapp.com/static'
appId: com.github.martin.electronupdaterexample
mac:
  category: your.app.category.type
  target:
    - zip
    - dmg
linux:
  category: Utility
  icon: icons/icons
  target:
    - AppImage
    - deb
appImage:
  systemIntegration: doNotAsk
win:
  target: nsis
  verifyUpdateCodeSignature: false
electronVersion: 5.0.12
